### ISSUE TITLE
feat: add scale option

### ISSUE THREAD

**Issue by josegonzalez** [deeplook/sparklines#21]
It would be great to be able to scale a series against a number. At the moment, I am adding a number to the end of the set, which makes everything scale against it, but also includes that number in the output.

**Comment by deeplook** [comment]
I'm not sure how much sense it would make to add any "computational" muscles to sparklines since you can always simply pass an alternative array of numbers.

**Comment by josegonzalez** [comment]
I just want it to scale the sparkline to 100, since it makes more sense when you're looking at multiple time-series if they all have the same scale :)

**Comment by deeplook** [comment]
Can you give an example, maybe, to illustrate more precisely?

**Comment by josegonzalez** [comment]
I have a [script](https://github.com/josegonzalez/rds-reservation-analyzer) that outputs utilization information for databases. Here is the output, which I scale to help visualize the actual resource usage.

```
$ bin/rds-reservation-analyzer -C memory --threshold 75 --sort-by percentage
instance identifier                     percentage  reserve    sparklines
------------------------------------  ------------  ---------  --------------------------------------------------------------------------------------------
production-buzzfeed                        41.7224  True       ▂▁▂▁▂▁▂▁▂▂▁▂▁▂▁▂▁▂▂▁▂▁▂▂▂▁▂▁▂▁▂▁▂▂▂▂▁▂▁▂▂▂▂▁▂▁▂▂▂▁▂▁▂▁▂▁▂▁▂▁▂▂▁▁▂▂▁▂▂▁▂▂▁▂▂▁▂▂▁▂▂▂▂▂▂▁▁▁▁▂▁█
production-blart                           76.2455  False      ▅▆▁▆▄▆▁▆▆▂▆▆▆▁▆▅▆▆▃▆▆▆▆▂▁▆▆▆▅▆▃▆▁▂▆▆▆▄▆▂▃▆▁▆▆▆▆▆▁▆▅▆▁▆▃▆▁▆▆▆▁▆▆▆▁▄▆▆▃▆▁▂▆▆▁▆▆▁▆▆▁▂▆▁▆▆▅▆▆▄▆█
production-manbearpig                      88.4585  False      ▂▂▁▂▂▂▁▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▁▂▂▂▁▂▂▂▁▂▂▂▁▂▂▂▂▂▂▂▂▂▁▂▂▁▂▂▁▂▂▁▂▂▂▂▂▂▂█
production-manbearpig-replica              92.4751  False      ▄▄▁▄▄▄▁▄▄▄▄▄▄▁▄▄▄▄▄▄▄▄▄▄▁▄▄▄▄▄▄▄▅▄▄▄▄▄▄▄▄▄▁▄▄▄▄▄▅▄▄▄▁▄▄▄▁▄▄▄▁▄▄▄▁▄▄▄▄▄▄▄▄▄▁▄▄▁▄▄▂▄▄▁▄▄▄▄▄▄▄█
production-keyboard                        95.8047  False      ▁▃▂▄▁▂▁▃▁▁▂▁▂▂▂▁▂▂▁▂▁▃▁▂▂▃▁▂▁▂▁▃▁▁▁▁▃▁▃▂▁▁▁▂▂▃▂▁▁▃▁▂▂▂▁▃▂▃▁▃▁▁▃▂▂▁▃▂▁▂▁▁▃▂▂▂▁▂▂▁▂▂▁▁▁▃▁▂▂▁▂█
```

**Comment by deeplook** [comment]
I see, thanks! But you still have only eight values (categories) per character (nine, if you would include blanks for 0), so it's nowhere as precise as the four digits in your percentage column, but well, that's the price to pay for ASCII.

You could scale the numbers before sending them to sparklines, but that would be a challenge in something like bash, sure... Have you considered writing a little "adaptor" Python script doing this? It might be faster than getting the feature into sparklines, at least from my side, since I'm busy with lots of other things now.

**Comment by josegonzalez** [comment]
Would you consider a PR for adding a `scale` option to this package?

**Comment by mkgs** [comment]
You can get the desired result by setting the `maximum` keyword argument to 100

**Comment by deeplook** [comment]
@mkgs, heck, you're right! I should use my own stuff more often. ;-)

```bash
$ sparklines 1 2 3 4 1 2 3 4
▁▃▆█▁▃▆█
$ sparklines -M 10 1 2 3 4 1 2 3 4
▁▂▃▃▁▂▃▃
```

**Comment by josegonzalez** [comment]
Ah, looks like that exists, but isn't available in the current release? Would it be possible to make a release, as per #18?

**Comment by deeplook** [comment]
@josegonzalez I'd be happy to make a new release, but I usually wait for a few features to accumulate. In this case I think I'd like to see #9 and the newly created #24.

**Comment by josegonzalez** [comment]
hokay :)
