### ISSUE TITLE
Scaling issues when num_lines > 1

### ISSUE THREAD

**Issue by mkgs** [deeplook/sparklines#22]
Values are incorrectly scaled when num_lines > 1, sometimes resulting in sparklines that are lower than expected, and failing on certain inputs, e.g. [0,1].

You can verify that running `sparklines([0,1], 2)` raises a `ZeroDivisionError`, while running `sparklines([0,100], 4)` produces `[' ▅', ' █', ' █', '▁█']`, when the correct output is `[' █', ' █', ' █', '▁█']`.

**Comment by deeplook** [comment]
Confirmed. I'll try to look at it quickly, but can't give a concrete estimate.
